### PR TITLE
Add the alive command.

### LINKED ISSUE #9: What shall be the first command?
What should it be?

### PR DESCRIPTION
**Pull request by ppwater01**
Please add some alive messages if you like. (You don't need to create a PR for it)

### CODE REVIEW

**Review by Tech-Expert-Wizard — COMMENTED** [review]
@ppwater01 Pretty good, also, thanks for adding message replying and "No such command" feedback. Let's have a look at Smokey's code to see what it would say when running `!!/alive`. @Victor-VosMottor @Ann-Zen What do you think?

**Comment by ppwater01** [comment]
@Tech-Expert-Wizard 
```
# --- Administration Commands --- #
ALIVE_MSG = [
    'Yup', 'You doubt me?', 'Of course', '... did I miss something?', 'plz send teh coffee',
    'Watching this endless list of new questions *never* gets boring', 'Kinda sorta',
    'You should totally drop that and use jQuery', r'¯\\_(ツ)\_/¯', '... good question',
]


# noinspection PyIncorrectDocstring
@command(aliases=["live"])
def alive():
    """
    Returns a string indicating the process is still active
    :return: A string
    """
    return random.choice(ALIVE_MSG)
```
**(smokey's code for alive)**

**Review by Tech-Expert-Wizard — APPROVED** [review]
@ppwater01 @Victor-VosMottor @Ann-Zen I think this is good with the new alive replies. Actually, the most importat part is that `event.message.reply(run(msg[3:]))` was added. However, I'd like to make a note. This wouldn't work with the prefix `@reopenbot ` so that's another reason why that prefix shouldn't be used.

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 @Victor-VosMottor @Ann-Zen After waiting for almost two days, I finally cannot continue to wait for someone else to come here and approve it. I'll just merge it.

**Pull request merged**
