### PR TITLE
Prefix Change

### LINKED ISSUE #2: What should the prefix for our bot be?
What should be the prefix for the bot? @Tech-Expert-Wizard @Ann-Zen

### PR DESCRIPTION
**Pull request by Tech-Expert-Wizard**
@ppwater01 @Victor-VosMottor @Ann-Zen I've changed the prefix from `@reopenBot` to either `rpb` or `!!/`. I know I probably ain't being really clear here so if I don't seem clear to you please have a look at the code. BTWI'm not Python expert, can anyone help with getting the command that is after  'rpb ' or '!!/'? Thanks!

### CODE REVIEW

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 @Victor-VosMottor @Ann-Zen Sorry for accidentally closing and reopening this.

**Review by ppwater01 — CHANGES_REQUESTED** [review]
Um, could we add reopenBot prefix too?

**Comment by ppwater01** [comment]
I'll just merge it.

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 I believe that our bot should me more similar to SmokeDetector, which doesn't have a prefix of `@SmokeDetector` or `@Smokey` or `@closeBot` or whatever something like that with a ping.

**Pull request merged**
