### PR TITLE
Prefix Change #2

### LINKED ISSUE #2: What should the prefix for our bot be?
What should be the prefix for the bot? @Tech-Expert-Wizard @Ann-Zen

### PR DESCRIPTION
**Pull request by Tech-Expert-Wizard**
@Victor-VosMottor @Ann-Zen Please comment on this pull request with your opinions. Thank you. P.S. @ppwater01 Please do not immediately take action without explanation. BTW this is also good general advice to everyone else. Thank you.

### CODE REVIEW

**Review by ppwater01 — COMMENTED** [review]
Hmm, can't we have a reopenBot prefix? I think we could have it. (And sorry for taking actions without explanations)

**Review by ppwater01 — COMMENTED** [review]
And just because *smokey doesn't have it* doesn't mean *we can't have it*.

**Comment by Tech-Expert-Wizard** [comment]
> 
> 
> Hmm, can't we have a reopenBot prefix? I think we could have it. (And sorry for taking actions without explanations)

@ppwater01 Can we please get the opinions of @Ann-Zen and @Victor-VosMottor?

**Comment by Tech-Expert-Wizard** [comment]
> 
> 
> And just because _smokey doesn't have it_ doesn't mean _we can't have it_.

@ppwater01 That's a valid point, but still... Let's get other people's opinions, okay? Thanks!

**Review by Tech-Expert-Wizard — COMMENTED** [review]
@Victor-VosMottor @Ann-Zen We would welcome your comments. Thank you.

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 @Victor-VosMottor @Ann-Zen Ugh.. No one's reviewing this, I'll just merge it.

**Pull request merged**
